// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: snail_job_grpc_service.proto

package com.aizuda.snailjob.common.core.grpc.auto;

public interface GrpcResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GrpcResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 reqId = 1;</code>
   * @return The reqId.
   */
  long getReqId();

  /**
   * <code>int32 status = 2;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>string message = 3;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string data = 4;</code>
   * @return The data.
   */
  java.lang.String getData();
  /**
   * <code>string data = 4;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
