// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: snail_job_grpc_service.proto

package com.aizuda.snailjob.common.core.grpc.auto;

public final class SnailJobGrpcService {
  private SnailJobGrpcService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Metadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Metadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Metadata_HeadersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Metadata_HeadersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GrpcSnailJobRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GrpcSnailJobRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GrpcResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GrpcResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034snail_job_grpc_service.proto\032\031google/p" +
      "rotobuf/any.proto\032\037google/protobuf/times" +
      "tamp.proto\"p\n\010Metadata\022\013\n\003uri\030\003 \001(\t\022\'\n\007h" +
      "eaders\030\007 \003(\0132\026.Metadata.HeadersEntry\032.\n\014" +
      "HeadersEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t" +
      ":\0028\001\"e\n\023GrpcSnailJobRequest\022\r\n\005reqId\030\001 \001" +
      "(\003\022\033\n\010metadata\030\002 \001(\0132\t.Metadata\022\"\n\004body\030" +
      "\003 \001(\0132\024.google.protobuf.Any\"`\n\nGrpcResul" +
      "t\022\r\n\005reqId\030\001 \001(\003\022\016\n\006status\030\002 \001(\005\022\017\n\007mess" +
      "age\030\003 \001(\t\022\"\n\004data\030\004 \001(\0132\024.google.protobu" +
      "f.AnyB-\n)com.aizuda.snailjob.common.core" +
      ".grpc.autoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_Metadata_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Metadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Metadata_descriptor,
        new java.lang.String[] { "Uri", "Headers", });
    internal_static_Metadata_HeadersEntry_descriptor =
      internal_static_Metadata_descriptor.getNestedTypes().get(0);
    internal_static_Metadata_HeadersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Metadata_HeadersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_GrpcSnailJobRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GrpcSnailJobRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GrpcSnailJobRequest_descriptor,
        new java.lang.String[] { "ReqId", "Metadata", "Body", });
    internal_static_GrpcResult_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GrpcResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GrpcResult_descriptor,
        new java.lang.String[] { "ReqId", "Status", "Message", "Data", });
    com.google.protobuf.AnyProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
